#!/usr/bin/env bash

dice=$1
sides=$2

if [ $# -gt 2 ]
then
	echo "Too many arguments! Will try $1 and $2 for # dice and # sides, respectively."
fi

# If not two arguments
if [ $# -lt 2 ] 
then
	# Prompt for input
	if [ $# -lt 1 ]
	then
		# If no first argument
		read -p "Input # dice to roll: " dice
	else
		echo "Too few arguments! Will try $1 for # dice."
	fi
	read -p "Input # sides per die: " sides
fi

# Validate positive integer inputs
while [[ ! $dice =~ ^[1-9][0-9]*$ ]]; do
	read -p "Dice # must be a positive integer. Try again: " dice
done

while [[ ! $sides =~ ^[1-9][0-9]*$ ]]; do
	read -p "Sides # must be a positive integer. Try again: " sides
done

# Roll dice
for(( i=1; i<=$dice; i++ )); do
	random_num=$((1 + $RANDOM % $sides))
	echo "Dice $i rolled a $random_num"
done